### ISSUE TITLE
Bug when WintabsClose on unsaved buffer that is open in another window.

### ISSUE THREAD

**Issue by jordwalke** [zefei/vim-wintabs#23]
1. `:e newFile.txt`
2. `vsplit`
3. Edit the split file (see changes appear in the other window too).
4. Try to `:WintabsClose`.
5. Watch it not succeed in closing it since it's open in another window. It is not in a broken state.

**Comment by jordwalke** [comment]
config:
```
set hidden
let g:tabSystem = 'wintabs'
let g:wintabs_autoclose=1
let g:wintabs_autoclose_vim=1
let g:wintabs_switchbuf='useopen,usetab'
let g:wintabs_ui_modified*
let g:wintabs_ui_active_higroup = 'TabLineSel'
```

**Comment by zefei** [comment]
Should be fixed in the latest commit. This is a very edge case that I can't fix completely due to how confirm/hidden interact with each other. The new behavior is that you can close a modified buffer if it's currently shown in another window or vimtab, with no confirm dialog. I think this behavior is less broken than not closing with no error/confirm.

Let me know if this is fixed for you, and if it feels "more correct" than before.

**Comment by jordwalke** [comment]
I'll check it out: For posterity here's the workaround I created. You might find it useful to handle some edge cases - I basically just detect whether or not there are unsaved changes before even calling `wintabs#close()`.

```
function MaybeCloseWinTab()
  if &modified
    let choice = confirm("File has unsaved changes!", "&Save\n&Cancel\n&Don't Save", 2)
    if choice == 3
      " Don't save: Reset the file then call WintabsClose
      execute "silent earlier 1f"
      call wintabs#close()
    elseif choice == 2 || choice == 0
      " Cancel
    elseif choice == 1
      execute ":w"
      call wintabs#close()
    endif
  else
    call wintabs#close()
  endif
endfunction
```

**Comment by zefei** [comment]
Closing this as I implemented your suggestion.
